import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "@/components/Header";
import FooterSection from "@/components/Footer";
import { Playfair_Display } from 'next/font/google';
import { Anton } from 'next/font/google';
import { Inter } from 'next/font/google';

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],   
  variable: '--font-playfair',
});

const anton = Anton({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-anton',
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-inter',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html
      lang="en"
      className={`${playfair.variable} ${anton.variable} ${inter.variable}`}
    >
      <body className={`${playfair.variable} ${anton.variable} ${inter.variable}`}>
        <Header/>
        {children}
         <FooterSection/>
      </body>
     
    </html>
  );
}
